### ISSUE TITLE
How to get description in search query ?

### ISSUE THREAD

**Issue by gietmxh** [MirazMac/YouScrape#1]
How can i get description of video in search query.

**Comment by MirazMac** [comment]
Well you can't. The limitation here is it depends on YouTube's internal AJAX endpoint. So it can only show the information it provides.

**Comment by gietmxh** [comment]
:D i think this project should change to curl the youtube for pc version. In the search query has description

**Comment by MirazMac** [comment]
Well, at first I started with the PC version. But the endpoints for PC version is not quite "scrape-friendly", responses are a bit bloated and changes frequently. That's why I've ended up with the mobile version. Its quite simple and straight-forward. However, thanks for your suggestion I'll look into the PC version again. Cheers :D
